//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceManagementSystem.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AttendanceManagementSystem.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absent.
        /// </summary>
        public static string Absent {
            get {
                return ResourceManager.GetString("Absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your choice : .
        /// </summary>
        public static string AskChoice {
            get {
                return ResourceManager.GetString("AskChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email - .
        /// </summary>
        public static string AskEmail {
            get {
                return ResourceManager.GetString("AskEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Employee details :.
        /// </summary>
        public static string AskEmployeeDetails {
            get {
                return ResourceManager.GetString("AskEmployeeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID - .
        /// </summary>
        public static string AskID {
            get {
                return ResourceManager.GetString("AskID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Employee Id to mark the attendance : .
        /// </summary>
        public static string AskIdForAttendance {
            get {
                return ResourceManager.GetString("AskIdForAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Manager details :.
        /// </summary>
        public static string AskManagerDetails {
            get {
                return ResourceManager.GetString("AskManagerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name - .
        /// </summary>
        public static string AskName {
            get {
                return ResourceManager.GetString("AskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add an employee? (Y/N) : .
        /// </summary>
        public static string AskToAddEmployee {
            get {
                return ResourceManager.GetString("AskToAddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        public static string AttendanceCollectionName {
            get {
                return ResourceManager.GetString("AttendanceCollectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  CheckIn successfull  .
        /// </summary>
        public static string CheckInSuccess {
            get {
                return ResourceManager.GetString("CheckInSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  CheckOut successfull .
        /// </summary>
        public static string CheckOutSuccess {
            get {
                return ResourceManager.GetString("CheckOutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://localhost:8081.
        /// </summary>
        public static string ConnectionEndPointUrl {
            get {
                return ResourceManager.GetString("ConnectionEndPointUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==.
        /// </summary>
        public static string ConnectionPrimaryKey {
            get {
                return ResourceManager.GetString("ConnectionPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee {0} has already checked-in today..
        /// </summary>
        public static string EmployeeAlreadyCheckedIn {
            get {
                return ResourceManager.GetString("EmployeeAlreadyCheckedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee {0} has already checked out for today..
        /// </summary>
        public static string EmployeeAlreadyCheckedOut {
            get {
                return ResourceManager.GetString("EmployeeAlreadyCheckedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string EmployeeCollectionName {
            get {
                return ResourceManager.GetString("EmployeeCollectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new employee details are not valid..
        /// </summary>
        public static string EmployeeInvalid {
            get {
                return ResourceManager.GetString("EmployeeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee {0} has not checked in today..
        /// </summary>
        public static string EmployeeNotCheckedIn {
            get {
                return ResourceManager.GetString("EmployeeNotCheckedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee with this id could not be found..
        /// </summary>
        public static string EmployeeNotFound {
            get {
                return ResourceManager.GetString("EmployeeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR!! .
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does {0} has a manager? (Y/N) - .
        /// </summary>
        public static string HasAManager {
            get {
                return ResourceManager.GetString("HasAManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Input!.
        /// </summary>
        public static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string LogCollectionName {
            get {
                return ResourceManager.GetString("LogCollectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee checked in with id : .
        /// </summary>
        public static string LogEmployeeCheckedIn {
            get {
                return ResourceManager.GetString("LogEmployeeCheckedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee checked out with id :.
        /// </summary>
        public static string LogEmployeeCheckedOut {
            get {
                return ResourceManager.GetString("LogEmployeeCheckedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Attendance document created for employee id : .
        /// </summary>
        public static string LogNewAttendanceCreated {
            get {
                return ResourceManager.GetString("LogNewAttendanceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New employee added with id : .
        /// </summary>
        public static string LogNewEmployeeAdded {
            get {
                return ResourceManager.GetString("LogNewEmployeeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to do .
        /// </summary>
        public static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Add a new employee.
        /// </summary>
        public static string OptionAddEmployee {
            get {
                return ResourceManager.GetString("OptionAddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Check In.
        /// </summary>
        public static string OptionCheckIn {
            get {
                return ResourceManager.GetString("OptionCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Check Out.
        /// </summary>
        public static string OptionCheckOut {
            get {
                return ResourceManager.GetString("OptionCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Exit.
        /// </summary>
        public static string OptionExit {
            get {
                return ResourceManager.GetString("OptionExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Mark attendance for existing employee.
        /// </summary>
        public static string OptionMarkAttendance {
            get {
                return ResourceManager.GetString("OptionMarkAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present.
        /// </summary>
        public static string Present {
            get {
                return ResourceManager.GetString("Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue..
        /// </summary>
        public static string PressAnyKey {
            get {
                return ResourceManager.GetString("PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue : .
        /// </summary>
        public static string PressKey {
            get {
                return ResourceManager.GetString("PressKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string QuestionMark {
            get {
                return ResourceManager.GetString("QuestionMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request was not processed. Please Try again..
        /// </summary>
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
    }
}
